// ============================================
// マスターデータ（資格・ドメイン・キノコ種）
// ============================================

import {
  DomainInfo,
  DomainId,
  DomainValues,
  MushroomSpecies,
  MushroomSpeciesId,
  CertificationMaster,
  CustomCertificationMeta,
  Cultivation,
  PhaseThresholds,
  Achievement,
} from "./types";

// ============================================
// 知識ドメイン定義
// ============================================

export const DOMAINS: Record<DomainId, DomainInfo> = {
  CS:  { id: "CS",  name: "コンピュータ科学基礎", shortName: "CS基礎",   description: "アルゴリズム、データ構造、計算理論" },
  NW:  { id: "NW",  name: "ネットワーク",         shortName: "NW",       description: "TCP/IP、ルーティング、プロトコル" },
  DB:  { id: "DB",  name: "データベース",         shortName: "DB",       description: "SQL、正規化、トランザクション" },
  SEC: { id: "SEC", name: "セキュリティ",         shortName: "SEC",      description: "暗号、認証、脅威対策" },
  OS:  { id: "OS",  name: "Linux/OS",            shortName: "OS",       description: "カーネル、シェル、プロセス管理" },
  CLD: { id: "CLD", name: "クラウド",             shortName: "CLD",      description: "仮想化、IaaS/PaaS、スケーリング" },
  PG:  { id: "PG",  name: "プログラミング",        shortName: "PG",       description: "OOP、関数型、設計パターン" },
  AI:  { id: "AI",  name: "AI/データ分析",        shortName: "AI",       description: "機械学習、統計、データ処理" },
  ARC: { id: "ARC", name: "システム設計",          shortName: "設計",     description: "アーキテクチャ、可用性、設計判断" },
  DEV: { id: "DEV", name: "開発プロセス",          shortName: "開発",     description: "Git、CI/CD、テスト、アジャイル" },
};

export const DOMAIN_LIST: DomainInfo[] = Object.values(DOMAINS);

// ============================================
// キノコ種定義
// ============================================

export const MUSHROOM_SPECIES: Record<string, MushroomSpecies> = {
  mushroom: {
    id: "mushroom",
    nameJa: "マッシュルーム",
    nameEn: "Agaricus bisporus",
    description: "万能で基本的なキノコ。どんな環境にも適応し、安定した形態を示す。",
    baseHue: 30,
    baseMorphology: { capDiameter: 0.6, capRoundness: 0.8, stipeLength: 0.4, stipeWidth: 0.5, gillDensity: 0.6, clusterCount: 1 },
  },
  enoki: {
    id: "enoki",
    nameJa: "エノキタケ",
    nameEn: "Flammulina velutipes",
    description: "細く長い柄に小さな傘が特徴。群生し、スクリプト的な手軽さを象徴する。",
    baseHue: 45,
    baseMorphology: { capDiameter: 0.2, capRoundness: 0.9, stipeLength: 0.9, stipeWidth: 0.1, gillDensity: 0.3, clusterCount: 8 },
  },
  shiitake: {
    id: "shiitake",
    nameJa: "シイタケ",
    nameEn: "Lentinula edodes",
    description: "原木栽培の代表格。地道なインフラ作業のように、着実に育つ。",
    baseHue: 25,
    baseMorphology: { capDiameter: 0.7, capRoundness: 0.4, stipeLength: 0.4, stipeWidth: 0.4, gillDensity: 0.8, clusterCount: 1 },
  },
  bunashimeji: {
    id: "bunashimeji",
    nameJa: "ブナシメジ",
    nameEn: "Hypsizygus tessellatus",
    description: "安定・堅実なキノコ。型安全な言語のように信頼性が高い。",
    baseHue: 220,
    baseMorphology: { capDiameter: 0.35, capRoundness: 0.7, stipeLength: 0.6, stipeWidth: 0.25, gillDensity: 0.5, clusterCount: 5 },
  },
  eringi: {
    id: "eringi",
    nameJa: "エリンギ",
    nameEn: "Pleurotus eryngii",
    description: "太い柄が特徴。ネットワークの太い幹線を象徴する。",
    baseHue: 35,
    baseMorphology: { capDiameter: 0.4, capRoundness: 0.3, stipeLength: 0.7, stipeWidth: 0.7, gillDensity: 0.4, clusterCount: 1 },
  },
  nameko: {
    id: "nameko",
    nameJa: "ナメコ",
    nameEn: "Pholiota microspora",
    description: "ぬめりのある粘膜に覆われた小型キノコ。データの粘着性を象徴する。",
    baseHue: 30,
    baseMorphology: { capDiameter: 0.3, capRoundness: 0.9, stipeLength: 0.3, stipeWidth: 0.2, gillDensity: 0.5, clusterCount: 6 },
  },
  hiratake: {
    id: "hiratake",
    nameJa: "ヒラタケ",
    nameEn: "Pleurotus ostreatus",
    description: "広く薄い傘が特徴。クラウドの広がりを象徴する。",
    baseHue: 210,
    baseMorphology: { capDiameter: 0.85, capRoundness: 0.2, stipeLength: 0.25, stipeWidth: 0.35, gillDensity: 0.7, clusterCount: 3 },
  },
  king_mushroom: {
    id: "king_mushroom",
    nameJa: "大型マッシュルーム",
    nameEn: "Agaricus bisporus (King)",
    description: "マッシュルームの上位種。基本情報から応用情報への進化を体現する。",
    baseHue: 28,
    baseMorphology: { capDiameter: 0.85, capRoundness: 0.75, stipeLength: 0.5, stipeWidth: 0.6, gillDensity: 0.8, clusterCount: 1 },
  },
  yamabushi: {
    id: "yamabushi",
    nameJa: "ヤマブシタケ",
    nameEn: "Hericium erinaceus",
    description: "珊瑚状の複雑な構造。システム設計の複雑さを象徴する。傘を持たない独特の形態。",
    baseHue: 40,
    baseMorphology: { capDiameter: 0.0, capRoundness: 0.0, stipeLength: 0.3, stipeWidth: 0.8, gillDensity: 0.0, clusterCount: 1 },
  },
  tamogitake: {
    id: "tamogitake",
    nameJa: "タモギタケ",
    nameEn: "Pleurotus cornucopiae var. citrinopileatus",
    description: "鮮やかな黄金色が特徴。AI/データの輝きを象徴する。",
    baseHue: 50,
    baseMorphology: { capDiameter: 0.6, capRoundness: 0.3, stipeLength: 0.4, stipeWidth: 0.3, gillDensity: 0.6, clusterCount: 4 },
  },
  maitake: {
    id: "maitake",
    nameJa: "マイタケ",
    nameEn: "Grifola frondosa",
    description: "波打つ多数の傘が重なり合う群生体。複数機能が有機的に育つ個人開発を象徴する。",
    baseHue: 20,
    baseMorphology: { capDiameter: 0.5, capRoundness: 0.1, stipeLength: 0.2, stipeWidth: 0.5, gillDensity: 0.3, clusterCount: 12 },
  },
};

// ============================================
// 資格マスターデータ
// ============================================

/**
 * 資格マスターデータ
 *
 * 系統（lineageGroup）：
 *  - "ipa"    : IPA系（基本情報 → 応用情報）
 *  - "aws"    : AWS系（CLF → SAA）
 *  - "linux"  : Linux系（単独）
 *  - "java"   : Java系（単独）
 *  - "network": ネットワーク系（単独、ただしAWSと配合で相性良い）
 *  - "db"     : データベース系（単独）
 *  - "python" : Python系（単独、G検定と配合で相性良い）
 *  - "ai"     : AI系（Python → G検定の流れ推奨）
 *  - "personal": 個人開発（どの系統にも属さない独立種）
 */
export const CERTIFICATIONS: CertificationMaster[] = [
  // ─── IPA系統（マッシュルーム系統樹） ───
  {
    id: "itpass",
    name: "ITパスポート",
    category: "IPA",
    mushroomSpeciesId: "mushroom",
    difficulty: 1,
    domains:         [1,  1,  1,  1,   0,  1,   0,  0,  1,   1] as DomainValues,
    estimatedDays: 45,
    description: "ITの基礎知識を幅広く問う国家試験。職種を問わずIT活用力を証明する入門資格。",
    tips: "IT未経験でも挑戦しやすい最初の一歩。基本情報への足がかりに最適です。",
    prerequisiteId: null,
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 270, colonizationInput: 1080, primordiaOutput: 432, fruitingTrigger: 162, maturationTotal: 2700, awakeningTotal: 3375, transformationTotal: 4320, legendaryTotal: 5400 },
  },
  {
    id: "sg",
    name: "情報セキュリティマネジメント",
    category: "IPA",
    mushroomSpeciesId: "mushroom",
    difficulty: 2,
    domains:         [1,  1,  1,  3,   1,  0,   0,  0,  1,   1] as DomainValues,
    estimatedDays: 60,
    description: "情報セキュリティの基本的な管理・運用スキルを証明する国家試験。",
    tips: "セキュリティ担当・管理者向け。ITパスポート取得後の次のステップとしても◎。",
    prerequisiteId: null,
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  {
    id: "fe",
    name: "基本情報技術者",
    category: "IPA",
    mushroomSpeciesId: "mushroom",
    difficulty: 2,
    domains:         [2,  1,  1,  1,   1,  0,   1,  0,  1,   1] as DomainValues,
    estimatedDays: 90,
    description: "ITエンジニアの登竜門。幅広い基礎知識を証明する国家試験。",
    tips: "IT業界で最初に取る資格として最適。他のすべての資格の土台になります。",
    prerequisiteId: null,
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "ap",
    name: "応用情報技術者",
    category: "IPA",
    mushroomSpeciesId: "king_mushroom",
    difficulty: 3,
    domains:         [3,  2,  2,  2,   1,  1,   2,  1,  2,   2] as DomainValues,
    estimatedDays: 120,
    description: "ITエンジニアとしての応用力を証明する国家試験。",
    tips: "基本情報技術者の合格後に挑戦するのが王道ルート。午後は選択問題なので得意分野を活かせます。",
    prerequisiteId: "fe",
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 720, colonizationInput: 2880, primordiaOutput: 1152, fruitingTrigger: 432, maturationTotal: 7200, awakeningTotal: 9000, transformationTotal: 11520, legendaryTotal: 14400 },
  },
  {
    id: "db_sp",
    name: "データベーススペシャリスト",
    category: "IPA",
    mushroomSpeciesId: "nameko",
    difficulty: 5,
    domains:         [3,  1,  5,  2,   1,  1,   1,  1,  3,   1] as DomainValues,
    estimatedDays: 180,
    description: "データベースの設計・構築・運用の高度スキルを証明する国家試験（高度区分）。",
    tips: "応用情報合格後の王道ルート。OSS-DBやORACLE MASTERとの相性も抜群。",
    prerequisiteId: "ap",
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 1080, colonizationInput: 4320, primordiaOutput: 1728, fruitingTrigger: 648, maturationTotal: 10800, awakeningTotal: 13500, transformationTotal: 17280, legendaryTotal: 21600 },
  },
  {
    id: "nw_sp",
    name: "ネットワークスペシャリスト",
    category: "IPA",
    mushroomSpeciesId: "eringi",
    difficulty: 5,
    domains:         [2,  5,  1,  2,   1,  2,   0,  0,  3,   1] as DomainValues,
    estimatedDays: 180,
    description: "ネットワークの設計・構築・運用の高度スキルを証明する国家試験（高度区分）。",
    tips: "応用情報＋CCNA合格後がおすすめ。NW設計の深い理解が求められます。",
    prerequisiteId: "ap",
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 1080, colonizationInput: 4320, primordiaOutput: 1728, fruitingTrigger: 648, maturationTotal: 10800, awakeningTotal: 13500, transformationTotal: 17280, legendaryTotal: 21600 },
  },
  {
    id: "sc",
    name: "情報処理安全確保支援士",
    category: "IPA",
    mushroomSpeciesId: "bunashimeji",
    difficulty: 5,
    domains:         [2,  2,  1,  5,   1,  1,   1,  0,  3,   2] as DomainValues,
    estimatedDays: 180,
    description: "サイバーセキュリティの専門家としての能力を証明する国家資格（登録制）。",
    tips: "応用情報合格者におすすめ。登録すれば独占名称で活躍可能。",
    prerequisiteId: "ap",
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 1080, colonizationInput: 4320, primordiaOutput: 1728, fruitingTrigger: 648, maturationTotal: 10800, awakeningTotal: 13500, transformationTotal: 17280, legendaryTotal: 21600 },
  },
  {
    id: "sa",
    name: "システムアーキテクト",
    category: "IPA",
    mushroomSpeciesId: "yamabushi",
    difficulty: 5,
    domains:         [3,  1,  2,  1,   1,  1,   2,  1,  5,   2] as DomainValues,
    estimatedDays: 180,
    description: "システムの全体設計・要件定義を牽引するアーキテクト向け国家試験（高度区分）。",
    tips: "応用情報合格後、上級SE・設計者を目指す方に。論述試験があるため文章力も鍛えられます。",
    prerequisiteId: "ap",
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 1080, colonizationInput: 4320, primordiaOutput: 1728, fruitingTrigger: 648, maturationTotal: 10800, awakeningTotal: 13500, transformationTotal: 17280, legendaryTotal: 21600 },
  },
  {
    id: "pm",
    name: "プロジェクトマネージャ（IPA）",
    category: "IPA",
    mushroomSpeciesId: "king_mushroom",
    difficulty: 5,
    domains:         [2,  1,  1,  1,   1,  1,   1,  0,  3,   5] as DomainValues,
    estimatedDays: 180,
    description: "プロジェクト全体を計画・推進する能力を証明する国家試験（高度区分）。",
    tips: "PMPと並ぶPM系最高峰。応用情報合格後、論述対策を重点的に。",
    prerequisiteId: "ap",
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 1080, colonizationInput: 4320, primordiaOutput: 1728, fruitingTrigger: 648, maturationTotal: 10800, awakeningTotal: 13500, transformationTotal: 17280, legendaryTotal: 21600 },
  },
  {
    id: "st",
    name: "ITストラテジスト",
    category: "IPA",
    mushroomSpeciesId: "king_mushroom",
    difficulty: 5,
    domains:         [2,  1,  1,  1,   1,  2,   1,  1,  5,   3] as DomainValues,
    estimatedDays: 200,
    description: "企業のIT戦略を策定する経営視点の高度国家試験。最難関区分の一つ。",
    tips: "IT企画・コンサル志向の方向け。論述の密度と経営知識が鍵。",
    prerequisiteId: "ap",
    lineageGroup: "ipa",
    phaseThresholds: { germinationInput: 1200, colonizationInput: 4800, primordiaOutput: 1920, fruitingTrigger: 720, maturationTotal: 12000, awakeningTotal: 15000, transformationTotal: 19200, legendaryTotal: 24000 },
  },
  // ─── AWS系統（ヒラタケ → ヤマブシタケ系統樹） ───
  {
    id: "aws_clf",
    name: "AWS クラウドプラクティショナー",
    category: "AWS",
    mushroomSpeciesId: "hiratake",
    difficulty: 2,
    domains:         [0,  1,  1,  1,   1,  3,   0,  0,  2,   1] as DomainValues,
    estimatedDays: 45,
    description: "AWSクラウドの基礎知識を証明するエントリーレベル認定。",
    tips: "AWS資格の入口。基本情報やLPICの知識があると学習がスムーズです。",
    prerequisiteId: null,
    lineageGroup: "aws",
    phaseThresholds: { germinationInput: 270, colonizationInput: 1080, primordiaOutput: 432, fruitingTrigger: 162, maturationTotal: 2700, awakeningTotal: 3375, transformationTotal: 4320, legendaryTotal: 5400 },
  },
  {
    id: "aws_saa",
    name: "AWS ソリューションアーキテクト アソシエイト",
    category: "AWS",
    mushroomSpeciesId: "yamabushi",
    difficulty: 3,
    domains:         [0,  2,  1,  2,   1,  3,   0,  0,  3,   1] as DomainValues,
    estimatedDays: 90,
    description: "AWSでのシステム設計スキルを証明する中級認定。",
    tips: "CLFの合格後に挑戦を。CCNAやLPICの知識があるとNW・OSの設問が楽になります。",
    prerequisiteId: "aws_clf",
    lineageGroup: "aws",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "aws_dva",
    name: "AWS デベロッパー アソシエイト",
    category: "AWS",
    mushroomSpeciesId: "hiratake",
    difficulty: 3,
    domains:         [1,  1,  1,  1,   1,  3,   2,  0,  2,   2] as DomainValues,
    estimatedDays: 90,
    description: "AWS上でのアプリケーション開発スキルを証明する中級認定。",
    tips: "CLF合格者＋Pythonや Java などの開発経験があるとスムーズ。",
    prerequisiteId: "aws_clf",
    lineageGroup: "aws",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "aws_soa",
    name: "AWS SysOps アドミニストレーター アソシエイト",
    category: "AWS",
    mushroomSpeciesId: "hiratake",
    difficulty: 3,
    domains:         [0,  2,  1,  1,   2,  3,   0,  0,  2,   2] as DomainValues,
    estimatedDays: 90,
    description: "AWSでの運用・監視・自動化スキルを証明する中級認定。",
    tips: "インフラ運用エンジニア向け。CLF合格後＋Linux知識があると◎。",
    prerequisiteId: "aws_clf",
    lineageGroup: "aws",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "aws_sap",
    name: "AWS ソリューションアーキテクト プロフェッショナル",
    category: "AWS",
    mushroomSpeciesId: "yamabushi",
    difficulty: 5,
    domains:         [1,  3,  2,  3,   2,  5,   1,  1,  5,   2] as DomainValues,
    estimatedDays: 150,
    description: "AWSでの大規模・複雑なシステム設計スキルを証明する上級認定。",
    tips: "SAA合格後、実務経験2年以上が目安。広範な知識と設計判断力が問われます。",
    prerequisiteId: "aws_saa",
    lineageGroup: "aws",
    phaseThresholds: { germinationInput: 900, colonizationInput: 3600, primordiaOutput: 1440, fruitingTrigger: 540, maturationTotal: 9000, awakeningTotal: 11250, transformationTotal: 14400, legendaryTotal: 18000 },
  },
  {
    id: "aws_dop",
    name: "AWS DevOpsエンジニア プロフェッショナル",
    category: "AWS",
    mushroomSpeciesId: "yamabushi",
    difficulty: 5,
    domains:         [1,  2,  1,  2,   2,  5,   2,  0,  3,   5] as DomainValues,
    estimatedDays: 150,
    description: "AWS上でのCI/CD・運用自動化の高度スキルを証明する上級認定。",
    tips: "DVA or SOA合格後がおすすめ。IaC・パイプライン設計の実務経験があると◎。",
    prerequisiteId: "aws_soa",
    lineageGroup: "aws",
    phaseThresholds: { germinationInput: 900, colonizationInput: 3600, primordiaOutput: 1440, fruitingTrigger: 540, maturationTotal: 9000, awakeningTotal: 11250, transformationTotal: 14400, legendaryTotal: 18000 },
  },
  // ─── Azure系統（新系統） ───
  {
    id: "az_900",
    name: "Azure Fundamentals (AZ-900)",
    category: "Azure",
    mushroomSpeciesId: "hiratake",
    difficulty: 1,
    domains:         [0,  1,  1,  1,   1,  3,   0,  0,  1,   1] as DomainValues,
    estimatedDays: 30,
    description: "Microsoft Azureクラウドの基礎知識を証明するエントリー認定。",
    tips: "Azure資格の入口。AWS CLFと似たレベル感で、クラウドの基本概念を学べます。",
    prerequisiteId: null,
    lineageGroup: "azure",
    phaseThresholds: { germinationInput: 180, colonizationInput: 720, primordiaOutput: 288, fruitingTrigger: 108, maturationTotal: 1800, awakeningTotal: 2250, transformationTotal: 2880, legendaryTotal: 3600 },
  },
  {
    id: "az_104",
    name: "Azure Administrator Associate (AZ-104)",
    category: "Azure",
    mushroomSpeciesId: "hiratake",
    difficulty: 3,
    domains:         [0,  2,  1,  2,   2,  3,   0,  0,  2,   2] as DomainValues,
    estimatedDays: 90,
    description: "Azure環境の管理・運用スキルを証明する中級認定。",
    tips: "AZ-900合格後に。仮想マシン・仮想ネットワーク・IDの理解が鍵。",
    prerequisiteId: "az_900",
    lineageGroup: "azure",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "az_305",
    name: "Azure Solutions Architect Expert (AZ-305)",
    category: "Azure",
    mushroomSpeciesId: "yamabushi",
    difficulty: 5,
    domains:         [1,  3,  2,  3,   2,  5,   1,  1,  5,   2] as DomainValues,
    estimatedDays: 120,
    description: "Azureでのシステム設計・アーキテクチャスキルを証明する上級認定。",
    tips: "AZ-104合格後がおすすめ。設計判断とコスト最適化の観点が問われます。",
    prerequisiteId: "az_104",
    lineageGroup: "azure",
    phaseThresholds: { germinationInput: 720, colonizationInput: 2880, primordiaOutput: 1152, fruitingTrigger: 432, maturationTotal: 7200, awakeningTotal: 9000, transformationTotal: 11520, legendaryTotal: 14400 },
  },
  // ─── Linux系統（独立） ───
  {
    id: "lpic1",
    name: "LPIC レベル1",
    category: "Linux",
    mushroomSpeciesId: "shiitake",
    difficulty: 2,
    domains:         [1,  1,  0,  1,   3,  0,   1,  0,  0,   1] as DomainValues,
    estimatedDays: 60,
    description: "Linuxの基本操作・管理スキルを証明する国際資格。",
    tips: "サーバーやインフラに関わるなら必須級。基本情報の後に取ると理解が深まります。",
    prerequisiteId: null,
    lineageGroup: "linux",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  {
    id: "lpic2",
    name: "LPIC レベル2",
    category: "Linux",
    mushroomSpeciesId: "shiitake",
    difficulty: 3,
    domains:         [1,  2,  1,  2,   5,  1,   1,  0,  2,   1] as DomainValues,
    estimatedDays: 90,
    description: "Linuxの中級管理スキル（カーネル・ストレージ・ネットワーク等）を証明。",
    tips: "LPIC1合格後、インフラエンジニア志向の方に。実機での操作経験が鍵。",
    prerequisiteId: "lpic1",
    lineageGroup: "linux",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "lpic3",
    name: "LPIC レベル3 Specialty",
    category: "Linux",
    mushroomSpeciesId: "shiitake",
    difficulty: 5,
    domains:         [1,  2,  1,  3,   5,  2,   1,  0,  3,   2] as DomainValues,
    estimatedDays: 120,
    description: "Linux管理の専門分野（Mixed Env / Security / Virtualization等）を極める上級認定。",
    tips: "LPIC2合格後、専門領域を深めたい方に。実務経験とともに挑戦を。",
    prerequisiteId: "lpic2",
    lineageGroup: "linux",
    phaseThresholds: { germinationInput: 720, colonizationInput: 2880, primordiaOutput: 1152, fruitingTrigger: 432, maturationTotal: 7200, awakeningTotal: 9000, transformationTotal: 11520, legendaryTotal: 14400 },
  },
  {
    id: "linuc1",
    name: "LinuC レベル1",
    category: "Linux",
    mushroomSpeciesId: "shiitake",
    difficulty: 2,
    domains:         [1,  1,  0,  1,   3,  1,   1,  0,  1,   1] as DomainValues,
    estimatedDays: 60,
    description: "日本発のLinux技術者認定。クラウド時代に対応したLinuxスキルを証明。",
    tips: "LPICと試験範囲が類似。日本語での受験・運営体制を重視する方に。",
    prerequisiteId: null,
    lineageGroup: "linux",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  // ─── ネットワーク系統（独立） ───
  {
    id: "ccna",
    name: "CCNA",
    category: "Network",
    mushroomSpeciesId: "eringi",
    difficulty: 3,
    domains:         [0,  3,  0,  2,   1,  1,   0,  0,  1,   0] as DomainValues,
    estimatedDays: 90,
    description: "ネットワークの設計・実装・運用スキルを証明するCisco認定資格。",
    tips: "ネットワーク専門の道へ進むなら。基本情報のNW知識が前提になります。",
    prerequisiteId: null,
    lineageGroup: "network",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "ccnp",
    name: "CCNP Enterprise",
    category: "Network",
    mushroomSpeciesId: "eringi",
    difficulty: 5,
    domains:         [1,  5,  0,  2,   1,  2,   0,  0,  3,   1] as DomainValues,
    estimatedDays: 150,
    description: "エンタープライズNW構築・運用の上級Cisco認定資格。",
    tips: "CCNA合格＋実務経験者向け。Core試験＋Concentration試験の組み合わせ。",
    prerequisiteId: "ccna",
    lineageGroup: "network",
    phaseThresholds: { germinationInput: 900, colonizationInput: 3600, primordiaOutput: 1440, fruitingTrigger: 540, maturationTotal: 9000, awakeningTotal: 11250, transformationTotal: 14400, legendaryTotal: 18000 },
  },
  // ─── データベース系統（独立） ───
  {
    id: "ossdb_silver",
    name: "OSS-DB Silver",
    category: "Database",
    mushroomSpeciesId: "nameko",
    difficulty: 2,
    domains:         [1,  0,  3,  1,   1,  0,   0,  0,  1,   0] as DomainValues,
    estimatedDays: 60,
    description: "PostgreSQLを中心としたOSSデータベースの技術力を証明する資格。",
    tips: "バックエンド開発やデータ分析に関わるなら。SQLの基礎知識があると良いです。",
    prerequisiteId: null,
    lineageGroup: "db",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  {
    id: "ossdb_gold",
    name: "OSS-DB Gold",
    category: "Database",
    mushroomSpeciesId: "nameko",
    difficulty: 4,
    domains:         [1,  1,  5,  2,   1,  1,   1,  0,  3,   1] as DomainValues,
    estimatedDays: 100,
    description: "PostgreSQLの設計・運用・パフォーマンスチューニングの上級認定。",
    tips: "Silver合格後＋実務経験あるとベスト。SQL・インデックス設計が深まります。",
    prerequisiteId: "ossdb_silver",
    lineageGroup: "db",
    phaseThresholds: { germinationInput: 600, colonizationInput: 2400, primordiaOutput: 960, fruitingTrigger: 360, maturationTotal: 6000, awakeningTotal: 7500, transformationTotal: 9600, legendaryTotal: 12000 },
  },
  {
    id: "oracle_bronze",
    name: "ORACLE MASTER Bronze DBA",
    category: "Database",
    mushroomSpeciesId: "nameko",
    difficulty: 2,
    domains:         [1,  0,  3,  1,   1,  0,   0,  0,  1,   0] as DomainValues,
    estimatedDays: 45,
    description: "Oracle Databaseの基礎知識・基本操作を証明するエントリー資格。",
    tips: "Oracle DB資格の入口。SQLの基礎を押さえたら次のSilverへ。",
    prerequisiteId: null,
    lineageGroup: "db",
    phaseThresholds: { germinationInput: 270, colonizationInput: 1080, primordiaOutput: 432, fruitingTrigger: 162, maturationTotal: 2700, awakeningTotal: 3375, transformationTotal: 4320, legendaryTotal: 5400 },
  },
  {
    id: "oracle_silver",
    name: "ORACLE MASTER Silver DBA",
    category: "Database",
    mushroomSpeciesId: "nameko",
    difficulty: 3,
    domains:         [1,  1,  5,  2,   1,  0,   1,  0,  2,   1] as DomainValues,
    estimatedDays: 90,
    description: "Oracle DBの管理・運用スキルを証明する中級資格。",
    tips: "Bronze合格後。バックアップ・リカバリ・セキュリティの理解が鍵。",
    prerequisiteId: "oracle_bronze",
    lineageGroup: "db",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "oracle_gold",
    name: "ORACLE MASTER Gold DBA",
    category: "Database",
    mushroomSpeciesId: "nameko",
    difficulty: 5,
    domains:         [2,  1,  5,  3,   1,  1,   1,  0,  3,   1] as DomainValues,
    estimatedDays: 150,
    description: "Oracle DBの設計・パフォーマンスチューニングの上級資格。",
    tips: "Silver合格後＋実務経験必須。DB設計の最適化・リカバリ戦略が問われます。",
    prerequisiteId: "oracle_silver",
    lineageGroup: "db",
    phaseThresholds: { germinationInput: 900, colonizationInput: 3600, primordiaOutput: 1440, fruitingTrigger: 540, maturationTotal: 9000, awakeningTotal: 11250, transformationTotal: 14400, legendaryTotal: 18000 },
  },
  // ─── プログラミング系統（独立） ───
  {
    id: "python3",
    name: "Python 3 エンジニア認定基礎試験",
    category: "Programming",
    mushroomSpeciesId: "enoki",
    difficulty: 1,
    domains:         [1,  0,  0,  0,   0,  0,   3,  1,  0,   1] as DomainValues,
    estimatedDays: 45,
    description: "Python言語の基礎力を証明する認定試験。",
    tips: "プログラミング初心者でも取りやすい。G検定やデータ分析への足がかりにも。",
    prerequisiteId: null,
    lineageGroup: "python",
    phaseThresholds: { germinationInput: 270, colonizationInput: 1080, primordiaOutput: 432, fruitingTrigger: 162, maturationTotal: 2700, awakeningTotal: 3375, transformationTotal: 4320, legendaryTotal: 5400 },
  },
  {
    id: "python_data",
    name: "Python 3 エンジニア認定データ分析試験",
    category: "Programming",
    mushroomSpeciesId: "tamogitake",
    difficulty: 2,
    domains:         [1,  0,  1,  0,   0,  0,   2,  3,  0,   1] as DomainValues,
    estimatedDays: 60,
    description: "Pythonを用いたデータ分析（NumPy/pandas/matplotlib等）の基礎を証明。",
    tips: "基礎試験合格後＋データ分析に興味がある方に。統計の基本も学べます。",
    prerequisiteId: "python3",
    lineageGroup: "python",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  {
    id: "java_bronze",
    name: "Java Programmer Bronze SE",
    category: "Programming",
    mushroomSpeciesId: "bunashimeji",
    difficulty: 1,
    domains:         [1,  0,  0,  0,   0,  0,   3,  0,  0,   0] as DomainValues,
    estimatedDays: 30,
    description: "Javaプログラミング言語の基礎文法を証明するエントリーレベル認定。",
    tips: "プログラミング初心者向け。Javaの基本文法とオブジェクト指向の入口に。",
    prerequisiteId: null,
    lineageGroup: "java",
    phaseThresholds: { germinationInput: 180, colonizationInput: 720, primordiaOutput: 288, fruitingTrigger: 108, maturationTotal: 1800, awakeningTotal: 2250, transformationTotal: 2880, legendaryTotal: 3600 },
  },
  {
    id: "java_silver",
    name: "Java Programmer Silver SE",
    category: "Programming",
    mushroomSpeciesId: "bunashimeji",
    difficulty: 2,
    domains:         [2,  0,  0,  0,   0,  0,   3,  0,  1,   1] as DomainValues,
    estimatedDays: 60,
    description: "Javaプログラミングの基本スキルを証明するOracle認定資格。",
    tips: "エンタープライズ系の開発をするなら。オブジェクト指向の理解が深まります。",
    prerequisiteId: "java_bronze",
    lineageGroup: "java",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  {
    id: "java_gold",
    name: "Java Programmer Gold SE",
    category: "Programming",
    mushroomSpeciesId: "bunashimeji",
    difficulty: 4,
    domains:         [3,  0,  1,  1,   0,  0,   5,  0,  3,   2] as DomainValues,
    estimatedDays: 120,
    description: "Javaの高度な機能（並行処理・ストリーム・モジュール等）を使いこなす上級認定。",
    tips: "Silver合格後、実務経験があると◎。設計・並行処理の理解が深まります。",
    prerequisiteId: "java_silver",
    lineageGroup: "java",
    phaseThresholds: { germinationInput: 720, colonizationInput: 2880, primordiaOutput: 1152, fruitingTrigger: 432, maturationTotal: 7200, awakeningTotal: 9000, transformationTotal: 11520, legendaryTotal: 14400 },
  },
  // ─── Ruby系統（独立） ───
  {
    id: "ruby_silver",
    name: "Ruby技術者認定試験 Silver",
    category: "Programming",
    mushroomSpeciesId: "enoki",
    difficulty: 2,
    domains:         [1,  0,  0,  0,   0,  0,   3,  0,  1,   1] as DomainValues,
    estimatedDays: 45,
    description: "Rubyプログラミングの基本文法・標準ライブラリの理解を証明する認定試験。",
    tips: "Ruby on Rails開発者におすすめ。Rubyらしい書き方も学べます。",
    prerequisiteId: null,
    lineageGroup: "ruby",
    phaseThresholds: { germinationInput: 270, colonizationInput: 1080, primordiaOutput: 432, fruitingTrigger: 162, maturationTotal: 2700, awakeningTotal: 3375, transformationTotal: 4320, legendaryTotal: 5400 },
  },
  {
    id: "ruby_gold",
    name: "Ruby技術者認定試験 Gold",
    category: "Programming",
    mushroomSpeciesId: "enoki",
    difficulty: 4,
    domains:         [2,  0,  0,  0,   0,  0,   5,  0,  3,   2] as DomainValues,
    estimatedDays: 90,
    description: "Rubyの高度な機能・メタプログラミング・設計パターンを問う上級認定。",
    tips: "Silver合格後、Rails等の実務経験があると深い理解に。",
    prerequisiteId: "ruby_silver",
    lineageGroup: "ruby",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  // ─── AI系統（Python → G検定の流れ推奨） ───
  {
    id: "g_cert",
    name: "G検定",
    category: "AI",
    mushroomSpeciesId: "tamogitake",
    difficulty: 3,
    domains:         [1,  0,  0,  0,   0,  1,   1,  3,  0,   0] as DomainValues,
    estimatedDays: 60,
    description: "ディープラーニングの基礎知識を証明するJDLA認定試験。",
    tips: "Python基礎試験の後に挑戦すると効率的。AI・機械学習の全体像が掴めます。",
    prerequisiteId: null,
    lineageGroup: "ai",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  {
    id: "genai_passport",
    name: "生成AIパスポート",
    category: "AI",
    mushroomSpeciesId: "tamogitake",
    difficulty: 1,
    domains:         [1,  0,  0,  1,   0,  1,   0,  3,  0,   1] as DomainValues,
    estimatedDays: 30,
    description: "生成AIの基礎知識と活用リテラシーを証明する一般社団法人生成AI活用普及協会(GUGA)の認定試験。",
    tips: "AI初学者におすすめ。生成AIの仕組み・活用法・リスクを網羅的に学べます。G検定の前段としても最適。",
    prerequisiteId: null,
    lineageGroup: "ai",
    phaseThresholds: { germinationInput: 180, colonizationInput: 720, primordiaOutput: 288, fruitingTrigger: 108, maturationTotal: 1800, awakeningTotal: 2250, transformationTotal: 2880, legendaryTotal: 3600 },
  },
  {
    id: "e_cert",
    name: "E資格",
    category: "AI",
    mushroomSpeciesId: "tamogitake",
    difficulty: 5,
    domains:         [2,  0,  1,  0,   0,  1,   3,  5,  1,   1] as DomainValues,
    estimatedDays: 150,
    description: "ディープラーニングの実装能力を証明するJDLA認定試験（エンジニア資格）。",
    tips: "G検定合格＋認定プログラム修了が受験条件。数学・実装力が求められます。",
    prerequisiteId: "g_cert",
    lineageGroup: "ai",
    phaseThresholds: { germinationInput: 900, colonizationInput: 3600, primordiaOutput: 1440, fruitingTrigger: 540, maturationTotal: 9000, awakeningTotal: 11250, transformationTotal: 14400, legendaryTotal: 18000 },
  },
  {
    id: "stat_2",
    name: "統計検定 2級",
    category: "AI",
    mushroomSpeciesId: "tamogitake",
    difficulty: 3,
    domains:         [1,  0,  1,  0,   0,  0,   1,  3,  0,   0] as DomainValues,
    estimatedDays: 60,
    description: "大学基礎レベルの統計学の知識・活用力を証明する検定試験。",
    tips: "データサイエンスの土台に。Python データ分析と併せて取ると強力な武器に。",
    prerequisiteId: null,
    lineageGroup: "ai",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  // ─── テスト系統（新） ───
  {
    id: "jstqb_fl",
    name: "JSTQB 認定テスト技術者 Foundation Level",
    category: "Testing",
    mushroomSpeciesId: "shiitake",
    difficulty: 2,
    domains:         [1,  0,  0,  1,   0,  0,   1,  0,  1,   3] as DomainValues,
    estimatedDays: 45,
    description: "ソフトウェアテスト技術者の基礎知識を証明する国際資格（ISTQB）。",
    tips: "テスト設計・QAに関わる方に。テスト技法の体系的な理解が得られます。",
    prerequisiteId: null,
    lineageGroup: "testing",
    phaseThresholds: { germinationInput: 270, colonizationInput: 1080, primordiaOutput: 432, fruitingTrigger: 162, maturationTotal: 2700, awakeningTotal: 3375, transformationTotal: 4320, legendaryTotal: 5400 },
  },
  {
    id: "jstqb_al",
    name: "JSTQB 認定テスト技術者 Advanced Level",
    category: "Testing",
    mushroomSpeciesId: "shiitake",
    difficulty: 4,
    domains:         [2,  0,  0,  1,   0,  0,   1,  0,  2,   5] as DomainValues,
    estimatedDays: 90,
    description: "テストマネジメント・テストアナリスト等の高度専門性を証明する上級認定。",
    tips: "Foundation合格＋実務経験3年以上が目安。テストリーダー志向の方に。",
    prerequisiteId: "jstqb_fl",
    lineageGroup: "testing",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  // ─── プロジェクト管理・ITIL系統（新） ───
  {
    id: "pmp",
    name: "PMP (Project Management Professional)",
    category: "PM",
    mushroomSpeciesId: "king_mushroom",
    difficulty: 4,
    domains:         [1,  0,  0,  0,   0,  1,   0,  0,  3,   5] as DomainValues,
    estimatedDays: 120,
    description: "PMIが認定する国際的なプロジェクトマネジメント資格。",
    tips: "PM実務経験が受験要件。PMBOKに基づく体系的な知識が身につきます。",
    prerequisiteId: null,
    lineageGroup: "pm",
    phaseThresholds: { germinationInput: 720, colonizationInput: 2880, primordiaOutput: 1152, fruitingTrigger: 432, maturationTotal: 7200, awakeningTotal: 9000, transformationTotal: 11520, legendaryTotal: 14400 },
  },
  {
    id: "itil_fnd",
    name: "ITIL 4 Foundation",
    category: "PM",
    mushroomSpeciesId: "mushroom",
    difficulty: 2,
    domains:         [1,  1,  0,  1,   0,  1,   0,  0,  2,   3] as DomainValues,
    estimatedDays: 30,
    description: "ITサービスマネジメントのベストプラクティスを学ぶ国際認定。",
    tips: "運用・サービスマネジメントに関わる方向け。DX時代にも通用する共通言語に。",
    prerequisiteId: null,
    lineageGroup: "pm",
    phaseThresholds: { germinationInput: 180, colonizationInput: 720, primordiaOutput: 288, fruitingTrigger: 108, maturationTotal: 1800, awakeningTotal: 2250, transformationTotal: 2880, legendaryTotal: 3600 },
  },
  // ─── 仮想化系統（新） ───
  {
    id: "vcp",
    name: "VCP (VMware Certified Professional)",
    category: "Virtualization",
    mushroomSpeciesId: "hiratake",
    difficulty: 3,
    domains:         [1,  2,  0,  1,   2,  3,   0,  0,  2,   1] as DomainValues,
    estimatedDays: 90,
    description: "VMware製品を用いた仮想化基盤の設計・運用スキルを証明する認定。",
    tips: "オンプレ仮想化基盤を扱うインフラエンジニア向け。LPIC知識があると◎。",
    prerequisiteId: null,
    lineageGroup: "virtualization",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  // ─── ビジネス・経理系統（新） ───
  {
    id: "boki3",
    name: "日商簿記 3級",
    category: "Business",
    mushroomSpeciesId: "shiitake",
    difficulty: 1,
    domains:         [0,  0,  0,  0,   0,  0,   0,  0,  0,   0] as DomainValues,
    estimatedDays: 30,
    description: "経理の基礎知識（仕訳・決算）を身につける入門資格。",
    tips: "ビジネスパーソンの基礎教養。社会人として数字を読む力がつきます。",
    prerequisiteId: null,
    lineageGroup: "business",
    phaseThresholds: { germinationInput: 180, colonizationInput: 720, primordiaOutput: 288, fruitingTrigger: 108, maturationTotal: 1800, awakeningTotal: 2250, transformationTotal: 2880, legendaryTotal: 3600 },
  },
  {
    id: "boki2",
    name: "日商簿記 2級",
    category: "Business",
    mushroomSpeciesId: "shiitake",
    difficulty: 2,
    domains:         [0,  0,  0,  0,   0,  0,   0,  1,  1,   0] as DomainValues,
    estimatedDays: 90,
    description: "商業簿記・工業簿記の実務レベル知識を証明する検定（企業の花形資格）。",
    tips: "3級合格後に。経理・財務系で最も広く求められる水準。",
    prerequisiteId: "boki3",
    lineageGroup: "business",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
  {
    id: "fp3",
    name: "FP技能士 3級",
    category: "Business",
    mushroomSpeciesId: "shiitake",
    difficulty: 1,
    domains:         [0,  0,  0,  0,   0,  0,   0,  0,  0,   0] as DomainValues,
    estimatedDays: 30,
    description: "ファイナンシャル・プランニング（税金・保険・年金等）の基礎資格。",
    tips: "自分自身のマネーリテラシー向上にも最適。営業・SS職の方にも有効。",
    prerequisiteId: null,
    lineageGroup: "business",
    phaseThresholds: { germinationInput: 180, colonizationInput: 720, primordiaOutput: 288, fruitingTrigger: 108, maturationTotal: 1800, awakeningTotal: 2250, transformationTotal: 2880, legendaryTotal: 3600 },
  },
  {
    id: "fp2",
    name: "FP技能士 2級",
    category: "Business",
    mushroomSpeciesId: "shiitake",
    difficulty: 2,
    domains:         [0,  0,  0,  0,   0,  0,   0,  0,  1,   0] as DomainValues,
    estimatedDays: 60,
    description: "FPの実務レベル知識を証明する検定。AFP認定研修の修了で実務家を目指せる。",
    tips: "3級合格後に。金融・保険業界や独立FP志向の方におすすめ。",
    prerequisiteId: "fp3",
    lineageGroup: "business",
    phaseThresholds: { germinationInput: 360, colonizationInput: 1440, primordiaOutput: 576, fruitingTrigger: 216, maturationTotal: 3600, awakeningTotal: 4500, transformationTotal: 5760, legendaryTotal: 7200 },
  },
  // ─── 個人開発（独立種） ───
  {
    id: "personal_dev",
    name: "個人開発プロジェクト",
    category: "PersonalDev",
    mushroomSpeciesId: "maitake",
    difficulty: 0 as any,
    domains:         [1,  0,  1,  0,   0,  1,   3,  0,  2,   3] as DomainValues,
    estimatedDays: 90,
    description: "自分のアプリ・OSS・ポートフォリオ等の個人開発プロジェクト。",
    tips: "どの資格とも独立して始められます。取得した資格の知識を配合で活かしましょう。",
    prerequisiteId: null,
    lineageGroup: "personal",
    phaseThresholds: { germinationInput: 540, colonizationInput: 2160, primordiaOutput: 864, fruitingTrigger: 324, maturationTotal: 5400, awakeningTotal: 6750, transformationTotal: 8640, legendaryTotal: 10800 },
  },
];

/** IDから資格を取得 */
export function getCertificationById(id: string): CertificationMaster | undefined {
  return CERTIFICATIONS.find(c => c.id === id);
}

/**
 * 栽培から資格情報を解決する（カスタム資格ならcustomCertを返す）。
 * 画面側でのnullチェックをこれに寄せると表示まわりがシンプルになる。
 */
export function resolveCultivationCert(
  cultivation: Pick<Cultivation, "certificationId" | "customCert">,
): CertificationMaster | CustomCertificationMeta & { id: string; category: string; prerequisiteId: string | null; lineageGroup: string } | undefined {
  if (cultivation.certificationId === "custom" && cultivation.customCert) {
    return {
      id: "custom",
      category: "Custom",
      prerequisiteId: null,
      lineageGroup: "custom",
      ...cultivation.customCert,
    };
  }
  return getCertificationById(cultivation.certificationId);
}

/** カスタム資格のテンプレート（ドメイン強度の初期値） */
export interface CustomCertTemplate {
  id: string;
  label: string;
  description: string;
  mushroomSpeciesId: MushroomSpeciesId;
  domains: DomainValues;
}

export const CUSTOM_CERT_TEMPLATES: CustomCertTemplate[] = [
  {
    id: "generic_it",
    label: "IT全般（幅広く）",
    description: "特定領域に偏らないIT系の資格・試験に",
    mushroomSpeciesId: "mushroom",
    domains: [2, 1, 1, 1, 1, 1, 1, 0, 1, 1] as DomainValues,
  },
  {
    id: "programming",
    label: "プログラミング / 言語系",
    description: "特定の言語・フレームワークの習得",
    mushroomSpeciesId: "enoki",
    domains: [1, 0, 0, 0, 0, 0, 3, 0, 1, 1] as DomainValues,
  },
  {
    id: "network",
    label: "ネットワーク / インフラ",
    description: "ルーター・プロトコル・インフラ構築",
    mushroomSpeciesId: "eringi",
    domains: [0, 3, 0, 2, 1, 1, 0, 0, 1, 0] as DomainValues,
  },
  {
    id: "database",
    label: "データベース / SQL",
    description: "DB設計・クエリチューニング",
    mushroomSpeciesId: "nameko",
    domains: [1, 0, 3, 1, 1, 0, 0, 0, 1, 0] as DomainValues,
  },
  {
    id: "cloud",
    label: "クラウド（AWS/GCP/Azure）",
    description: "クラウドサービス認定や運用設計",
    mushroomSpeciesId: "hiratake",
    domains: [0, 2, 1, 2, 1, 3, 0, 0, 2, 1] as DomainValues,
  },
  {
    id: "security",
    label: "セキュリティ",
    description: "情報セキュリティ・脆弱性診断",
    mushroomSpeciesId: "bunashimeji",
    domains: [1, 2, 1, 3, 1, 1, 0, 0, 1, 1] as DomainValues,
  },
  {
    id: "ai_data",
    label: "AI / データ分析",
    description: "機械学習・データサイエンス系",
    mushroomSpeciesId: "tamogitake",
    domains: [1, 0, 1, 0, 0, 1, 1, 3, 0, 0] as DomainValues,
  },
  {
    id: "personal_dev",
    label: "個人開発 / 自習プロジェクト",
    description: "自分のつくりたいものを形にする",
    mushroomSpeciesId: "maitake",
    domains: [1, 0, 1, 0, 0, 1, 3, 0, 2, 3] as DomainValues,
  },
  {
    id: "other",
    label: "その他（IT以外も可）",
    description: "語学・会計・資格全般など",
    mushroomSpeciesId: "shiitake",
    domains: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0] as DomainValues,
  },
];

/** 予想学習日数からPhase閾値を生成（既存マスターの比率に合わせた） */
export function derivePhaseThresholds(estimatedDays: number): PhaseThresholds {
  const d = Math.max(1, estimatedDays);
  return {
    germinationInput: Math.round(d * 6),
    colonizationInput: Math.round(d * 24),
    primordiaOutput: Math.round(d * 9.6),
    fruitingTrigger: Math.round(d * 3.6),
    maturationTotal: Math.round(d * 60),
    awakeningTotal: Math.round(d * 75),
    transformationTotal: Math.round(d * 96),
    legendaryTotal: Math.round(d * 120),
  };
}

/** カスタム資格メタを生成 */
export function buildCustomCertMeta(params: {
  name: string;
  description?: string;
  tips?: string;
  templateId: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  estimatedDays: number;
}): CustomCertificationMeta {
  const tpl = CUSTOM_CERT_TEMPLATES.find((t) => t.id === params.templateId)
    ?? CUSTOM_CERT_TEMPLATES[0];
  return {
    name: params.name.trim() || "自由目標",
    description: params.description?.trim() || "ユーザーが自由に設定した学習目標",
    tips: params.tips?.trim() || "毎日少しずつ、自分のペースで進めましょう。",
    mushroomSpeciesId: tpl.mushroomSpeciesId,
    difficulty: params.difficulty,
    domains: [...tpl.domains] as DomainValues,
    estimatedDays: Math.max(1, params.estimatedDays),
    phaseThresholds: derivePhaseThresholds(params.estimatedDays),
  };
}

/** IDからキノコ種を取得 */
export function getMushroomSpecies(id: string): MushroomSpecies | undefined {
  return MUSHROOM_SPECIES[id];
}

// ============================================
// 実績マスターデータ
// ============================================

export const ACHIEVEMENTS: Achievement[] = [
  // ─────────────────────────────
  // 栽培系（Cultivation）
  // ─────────────────────────────
  {
    id: "first_sprout",
    name: "発芽の兆し",
    description: "初めて学習を記録してキノコの栽培を開始",
    category: "cultivation",
    condition: "学習記録を1回つける",
    rewardItemId: "petri_dish",
    rewardItemName: "シャーレ",
    icon: "sprout",
  },
  {
    id: "phase_colonization",
    name: "菌糸蔓延",
    description: "キノコをPhase 3（菌糸蔓延）まで育てる",
    category: "cultivation",
    condition: "1つの栽培をPhase 3以上に到達させる",
    rewardItemId: "substrate_bag",
    rewardItemName: "培地バッグ",
    icon: "git-branch",
  },
  {
    id: "phase_primordia",
    name: "原基形成",
    description: "キノコをPhase 4（原基形成）まで育てる",
    category: "cultivation",
    condition: "1つの栽培をPhase 4以上に到達させる",
    rewardItemId: "hygrometer",
    rewardItemName: "温湿度計",
    icon: "zap",
  },
  {
    id: "first_flush",
    name: "First Flush",
    description: "初めて子実体を成熟（Phase 6）まで育てる",
    category: "cultivation",
    condition: "1つの栽培をPhase 6に到達させる",
    rewardItemId: "shelf_basic",
    rewardItemName: "基本展示棚",
    icon: "award",
  },
  {
    id: "first_harvest",
    name: "初収穫",
    description: "育てたキノコを収穫する",
    category: "cultivation",
    condition: "1体のキノコを収穫",
    rewardItemId: "basket",
    rewardItemName: "収穫カゴ",
    icon: "package",
  },
  {
    id: "mycelium_network",
    name: "Mycelium Network",
    description: "3種類の資格キノコを収穫",
    category: "cultivation",
    condition: "収穫済みキノコ3体",
    rewardItemId: "wallpaper_mycelium",
    rewardItemName: "菌糸壁紙",
    icon: "network",
  },
  {
    id: "master_cultivator",
    name: "Master Cultivator",
    description: "5種類の異なるキノコ種を収穫",
    category: "cultivation",
    condition: "5種の異なるキノコ種（シイタケ・エノキ等）を収穫",
    rewardItemId: "lab_coat",
    rewardItemName: "白衣ハンガー",
    icon: "trophy",
  },
  {
    id: "big_cap",
    name: "巨大子実体",
    description: "傘径1.0以上の大型キノコを収穫",
    category: "cultivation",
    condition: "capDiameter ≥ 1.0 のキノコを1体収穫",
    rewardItemId: "caliper",
    rewardItemName: "計測キャリパー",
    icon: "maximize",
  },
  {
    id: "quick_harvest",
    name: "速成培養",
    description: "30日以内に1つのキノコを完成させる",
    category: "cultivation",
    condition: "開始から30日以内に収穫",
    rewardItemId: "stopwatch",
    rewardItemName: "タイマー",
    icon: "zap",
  },
  {
    id: "multi_cultivation",
    name: "並列栽培者",
    description: "同時に3つ以上の栽培を進める",
    category: "cultivation",
    condition: "同時に栽培中のキノコが3体以上",
    rewardItemId: "rack_shelf",
    rewardItemName: "多段培養棚",
    icon: "layers",
  },

  // ─────────────────────────────
  // 配合系（Mating）
  // ─────────────────────────────
  {
    id: "first_mating",
    name: "Plasmogamy",
    description: "初めて菌糸接合（配合）を行う",
    category: "cultivation",
    condition: "栽培開始時に配合相手を選択",
    rewardItemId: "petri_mating",
    rewardItemName: "接合シャーレ",
    icon: "git-merge",
  },
  {
    id: "strong_mating",
    name: "強接合",
    description: "共有ドメイン4つ以上の強い配合を行う",
    category: "cultivation",
    condition: "strong適合（共有4ドメイン以上）で配合",
    rewardItemId: "gene_chart",
    rewardItemName: "交配型チャート",
    icon: "link",
  },
  {
    id: "mating_master",
    name: "配合師",
    description: "5回の配合を実施する",
    category: "cultivation",
    condition: "配合ありの栽培を累計5回開始",
    rewardItemId: "breeding_journal",
    rewardItemName: "交配日誌",
    icon: "book-open",
  },

  // ─────────────────────────────
  // 学習継続系（Streak）
  // ─────────────────────────────
  {
    id: "streak_3",
    name: "発芽の鼓動",
    description: "3日続けて学習を記録。菌糸がゆっくり基質に広がり始めました",
    category: "study",
    condition: "3日連続で記録",
    rewardItemId: "sticky_note",
    rewardItemName: "付箋メモ",
    icon: "calendar",
  },
  {
    id: "streak_7",
    name: "継続の菌糸",
    description: "7日続けて学習を記録。菌糸ネットワークが順調に育っています（休眠チケット +1）",
    category: "study",
    condition: "7日連続で記録",
    rewardItemId: "flame_badge",
    rewardItemName: "炎バッジ",
    icon: "flame",
  },
  {
    id: "streak_30",
    name: "培養のリズム",
    description: "30日の学習リズムが身につきました。休む日があっても大丈夫（休眠チケット合計 +3）",
    category: "study",
    condition: "30日連続で記録",
    rewardItemId: "clean_bench",
    rewardItemName: "クリーンベンチ",
    icon: "zap",
  },
  {
    id: "streak_100",
    name: "深く根付いた菌糸体",
    description: "100日の学習を積み上げました。もう三日休んでも揺らがない強い根です（休眠チケット合計 +6）",
    category: "study",
    condition: "100日連続で記録",
    rewardItemId: "trophy_gold",
    rewardItemName: "ゴールドトロフィー",
    icon: "crown",
  },

  // ─────────────────────────────
  // 累計学習時間系（Total Minutes）
  // ─────────────────────────────
  {
    id: "total_10h",
    name: "10時間培養",
    description: "累計10時間の学習を達成",
    category: "study",
    condition: "累計学習時間が600分以上",
    rewardItemId: "clock_simple",
    rewardItemName: "シンプル時計",
    icon: "clock",
  },
  {
    id: "total_50h",
    name: "50時間培養",
    description: "累計50時間の学習を達成",
    category: "study",
    condition: "累計学習時間が3,000分以上",
    rewardItemId: "hourglass",
    rewardItemName: "砂時計",
    icon: "hourglass",
  },
  {
    id: "total_100h",
    name: "百時間培養",
    description: "累計100時間の学習を達成",
    category: "study",
    condition: "累計学習時間が6,000分以上",
    rewardItemId: "autoclave",
    rewardItemName: "オートクレーブ",
    icon: "clock",
  },
  {
    id: "total_500h",
    name: "五百時間の森",
    description: "累計500時間の学習を達成",
    category: "study",
    condition: "累計学習時間が30,000分以上",
    rewardItemId: "forest_tapestry",
    rewardItemName: "森林タペストリー",
    icon: "trees",
  },
  {
    id: "deep_dive",
    name: "没頭の一日",
    description: "1日にたっぷり学習した日の記念。この後は休息も大切に——睡眠と休憩が記憶を定着させます",
    category: "study",
    condition: "同じ日に累計240分以上記録",
    rewardItemId: "focus_candle",
    rewardItemName: "集中のキャンドル",
    icon: "target",
  },

  // ─────────────────────────────
  // インプット/アウトプット系
  // ─────────────────────────────
  {
    id: "first_output",
    name: "初アウトプット",
    description: "初めてアウトプットを記録する",
    category: "study",
    condition: "アウトプット記録を1回つける",
    rewardItemId: "pen",
    rewardItemName: "羽根ペン",
    icon: "pen-tool",
  },
  {
    id: "output_10",
    name: "アウトプッター",
    description: "アウトプットを10回記録する",
    category: "study",
    condition: "アウトプット記録を累計10回",
    rewardItemId: "whiteboard",
    rewardItemName: "ホワイトボード",
    icon: "edit-3",
  },
  {
    id: "balanced_one_day",
    name: "黄金比の日",
    description: "1日でI/Oバランスを理想（6:4）に近づける",
    category: "study",
    condition: "同じ日のInput:Output比が5:5〜7:3の範囲で1時間以上記録",
    rewardItemId: "balance_scale",
    rewardItemName: "天秤",
    icon: "scale",
  },
  {
    id: "variety_5",
    name: "多彩な学習",
    description: "5種類以上の種別で記録する",
    category: "study",
    condition: "異なる種別名を累計5種類記録",
    rewardItemId: "spice_rack",
    rewardItemName: "スパイスラック",
    icon: "palette",
  },
  {
    id: "variety_10",
    name: "博学の胞子",
    description: "10種類以上の種別で記録する",
    category: "study",
    condition: "異なる種別名を累計10種類記録",
    rewardItemId: "encyclopedia",
    rewardItemName: "百科事典",
    icon: "book",
  },

  // ─────────────────────────────
  // ロードマップ系
  // ─────────────────────────────
  {
    id: "roadmap_first_task",
    name: "最初の一歩",
    description: "学習ロードマップのタスクを初めて完了する",
    category: "study",
    condition: "ロードマップのタスクを1つ完了",
    rewardItemId: "map_pin",
    rewardItemName: "ロードマップピン",
    icon: "map-pin",
  },
  {
    id: "roadmap_first_chapter",
    name: "章を踏破",
    description: "学習ロードマップの章を初めてクリアする",
    category: "study",
    condition: "ロードマップの1つの章のタスクを全て完了",
    rewardItemId: "chapter_ribbon",
    rewardItemName: "章の栞（しおり）",
    icon: "bookmark",
  },
  {
    id: "roadmap_tasks_10",
    name: "着実な積み上げ",
    description: "ロードマップのタスクを10個完了する",
    category: "study",
    condition: "ロードマップのタスクを累計10個完了",
    rewardItemId: "milestone_stone",
    rewardItemName: "マイルストーン石",
    icon: "layers",
  },
  {
    id: "roadmap_tasks_50",
    name: "踏破者",
    description: "ロードマップのタスクを50個完了する",
    category: "study",
    condition: "ロードマップのタスクを累計50個完了",
    rewardItemId: "compass",
    rewardItemName: "真鍮の羅針盤",
    icon: "compass",
  },
  {
    id: "roadmap_complete",
    name: "ロードマップ踏破",
    description: "1つのロードマップの全章を完了する",
    category: "study",
    condition: "1つのロードマップの全タスクを完了",
    rewardItemId: "summit_flag",
    rewardItemName: "登頂の旗",
    icon: "flag",
  },

  // ─────────────────────────────
  // ソーシャル系
  // ─────────────────────────────
  {
    id: "spore_liberator",
    name: "Spore Liberator",
    description: "他人の部屋を10件訪問する",
    category: "social",
    condition: "部屋訪問10件",
    rewardItemId: "spore_canister",
    rewardItemName: "胞子キャニスター",
    icon: "users",
  },
];

/** IDから実績を取得 */
export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find(a => a.id === id);
}
